name: Build JavaDoc

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build JavaDoc with Maven
        run: mvn -B javadoc:javadoc

      - name: Copy JavaDoc to /docs
        run: |
          rm -rf docs
          mkdir docs
          cp -r target/site/apidocs/* docs/